# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd:\CodeCode\UiModern\GUI\mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1155, 631)
        MainWindow.setStyleSheet("*{\n"
"    font-family: \"Inter\", \"Segoe UI\", sans-serif;\n"
"    font-size: 14px;\n"
"}\n"
"#centralwidget {\n"
"    border-radius: 8px;\n"
"    background-color: rgb(255, 255, 255);\n"
"}\n"
"#navFrame {\n"
"    margin: 0px;\n"
"    background-color: #f1f1f1;\n"
"    border-bottom-left-radius: 8px;\n"
"\n"
"}\n"
"QLabel {\n"
"    font-family: \"Poppins\", \"Segoe UI\", sans-serif;\n"
"    font-size: 14px;\n"
"    font-weight: 400;\n"
"}\n"
"QLabel.title {\n"
"    font-size: 24px;\n"
"    font-weight: 600;\n"
" }\n"
"QLabel.subtitle {\n"
"    font-size: 16px;\n"
"    font-weight: 500;\n"
"}\n"
"QLineEdit {\n"
"    border: 1px solid #404040;\n"
"    border-radius: 4px;\n"
"     font-family: \"Open Sans\", \"Segoe UI\", sans-serif;\n"
"    font-size: 14px;\n"
"    padding: 2px;\n"
"}\n"
"QLineEdit:focus {\n"
"    border: 2px solid rgb(72, 72, 72);\n"
"}\n"
"QPlainTextEdit {\n"
"    border: 1px solid #404040;\n"
"    border-radius: 4px;\n"
"    padding: 8px;\n"
"    font-family: \"JetBrains Mono\", \"Fira Code\", \"Consolas\", monospace;\n"
"    font-size: 13px;\n"
"    line-height: 1.4;       \n"
" }\n"
"QPlainTextEdit:focus {\n"
"    border: 2px solid rgb(72, 72, 72);\n"
"}")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStyleSheet("")
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.titleFrame = QtWidgets.QFrame(self.centralwidget)
        self.titleFrame.setMinimumSize(QtCore.QSize(0, 0))
        self.titleFrame.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.titleFrame.setStyleSheet("QPushButton {\n"
"    border:none;\n"
"    font-size: 12px;\n"
"    padding: 5px;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgba(141, 141, 141, 0.3);\n"
"    border-color: #3daee9;\n"
"}\n"
"#titleFrame {\n"
"    border-top-right-radius: 8px;\n"
"    border-top-left-radius: 8px;\n"
"    background-color: #f3f3f3;\n"
"}\n"
"")
        self.titleFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.titleFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.titleFrame.setObjectName("titleFrame")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.titleFrame)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(10)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem = QtWidgets.QSpacerItem(1020, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.minimizeBtn = QtWidgets.QPushButton(self.titleFrame)
        self.minimizeBtn.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/nav/icons/minus-svgrepo-com.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.minimizeBtn.setIcon(icon)
        self.minimizeBtn.setIconSize(QtCore.QSize(20, 20))
        self.minimizeBtn.setObjectName("minimizeBtn")
        self.horizontalLayout_2.addWidget(self.minimizeBtn)
        self.maximizeBtn = QtWidgets.QPushButton(self.titleFrame)
        self.maximizeBtn.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/nav/icons/square-svgrepo-com.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.maximizeBtn.setIcon(icon1)
        self.maximizeBtn.setIconSize(QtCore.QSize(20, 20))
        self.maximizeBtn.setObjectName("maximizeBtn")
        self.horizontalLayout_2.addWidget(self.maximizeBtn)
        self.closeBtn = QtWidgets.QPushButton(self.titleFrame)
        self.closeBtn.setStyleSheet("QPushButton::hover{\n"
"    background-color: rgb(255, 5, 59);\n"
"    border-top-right-radius: 8px;\n"
"}")
        self.closeBtn.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/nav/icons/close-mini-1522-svgrepo-com.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.closeBtn.setIcon(icon2)
        self.closeBtn.setIconSize(QtCore.QSize(20, 20))
        self.closeBtn.setObjectName("closeBtn")
        self.horizontalLayout_2.addWidget(self.closeBtn)
        self.verticalLayout.addWidget(self.titleFrame)
        self.frame_2 = QtWidgets.QFrame(self.centralwidget)
        self.frame_2.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame_2)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.navFrame = QtWidgets.QFrame(self.frame_2)
        self.navFrame.setMinimumSize(QtCore.QSize(0, 0))
        self.navFrame.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.navFrame.setStyleSheet("QPushButton {\n"
"    border:none;\n"
"    text-align: left;\n"
"    font-size: 12px;\n"
"    padding: 5px;\n"
"}\n"
"QPushButton:hover {\n"
"    border-radius:8px;\n"
"    background-color: #e1e1e1;\n"
"    border-color: #3daee9;\n"
"}\n"
"QPushButton:checked {\n"
"    background-color: #e1e1e1;\n"
"    border-radius:8px;\n"
"}")
        self.navFrame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.navFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.navFrame.setLineWidth(0)
        self.navFrame.setObjectName("navFrame")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.navFrame)
        self.verticalLayout_2.setContentsMargins(2, 0, 2, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.homeBtn = QtWidgets.QPushButton(self.navFrame)
        self.homeBtn.setEnabled(True)
        self.homeBtn.setMinimumSize(QtCore.QSize(0, 45))
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/nav/icons/home-svgrepo-com.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.homeBtn.setIcon(icon3)
        self.homeBtn.setIconSize(QtCore.QSize(20, 20))
        self.homeBtn.setCheckable(True)
        self.homeBtn.setChecked(True)
        self.homeBtn.setObjectName("homeBtn")
        self.verticalLayout_2.addWidget(self.homeBtn)
        self.settingsBtn = QtWidgets.QPushButton(self.navFrame)
        self.settingsBtn.setMinimumSize(QtCore.QSize(0, 45))
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/nav/icons/settings-svgrepo-com.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.settingsBtn.setIcon(icon4)
        self.settingsBtn.setIconSize(QtCore.QSize(20, 20))
        self.settingsBtn.setCheckable(True)
        self.settingsBtn.setObjectName("settingsBtn")
        self.verticalLayout_2.addWidget(self.settingsBtn)
        self.contactBtn = QtWidgets.QPushButton(self.navFrame)
        self.contactBtn.setMinimumSize(QtCore.QSize(0, 45))
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/nav/icons/support-svgrepo-com.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.contactBtn.setIcon(icon5)
        self.contactBtn.setIconSize(QtCore.QSize(20, 20))
        self.contactBtn.setCheckable(True)
        self.contactBtn.setObjectName("contactBtn")
        self.verticalLayout_2.addWidget(self.contactBtn)
        self.helpBtn = QtWidgets.QPushButton(self.navFrame)
        self.helpBtn.setMinimumSize(QtCore.QSize(0, 45))
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/nav/icons/help-circle-svgrepo-com.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.helpBtn.setIcon(icon6)
        self.helpBtn.setIconSize(QtCore.QSize(20, 20))
        self.helpBtn.setCheckable(True)
        self.helpBtn.setObjectName("helpBtn")
        self.verticalLayout_2.addWidget(self.helpBtn)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem1)
        self.horizontalLayout.addWidget(self.navFrame)
        self.frame_4 = QtWidgets.QFrame(self.frame_2)
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.gridLayout = QtWidgets.QGridLayout(self.frame_4)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setSpacing(0)
        self.gridLayout.setObjectName("gridLayout")
        self.main_stacked_widget = QtWidgets.QStackedWidget(self.frame_4)
        self.main_stacked_widget.setObjectName("main_stacked_widget")
        self.home_page = QtWidgets.QWidget()
        self.home_page.setObjectName("home_page")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.home_page)
        self.verticalLayout_3.setContentsMargins(-1, -1, -1, 5)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label = QtWidgets.QLabel(self.home_page)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout_3.addWidget(self.label)
        self.tableView = QtWidgets.QTableView(self.home_page)
        self.tableView.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tableView.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.tableView.setObjectName("tableView")
        self.verticalLayout_3.addWidget(self.tableView)
        self.frame = QtWidgets.QFrame(self.home_page)
        self.frame.setObjectName("frame")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_selected = QtWidgets.QLabel(self.frame)
        self.label_selected.setTextFormat(QtCore.Qt.RichText)
        self.label_selected.setObjectName("label_selected")
        self.horizontalLayout_3.addWidget(self.label_selected)
        self.label_success = QtWidgets.QLabel(self.frame)
        self.label_success.setTextFormat(QtCore.Qt.RichText)
        self.label_success.setObjectName("label_success")
        self.horizontalLayout_3.addWidget(self.label_success)
        self.label_failed = QtWidgets.QLabel(self.frame)
        self.label_failed.setTextFormat(QtCore.Qt.RichText)
        self.label_failed.setObjectName("label_failed")
        self.horizontalLayout_3.addWidget(self.label_failed)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem2)
        self.verticalLayout_3.addWidget(self.frame)
        self.main_stacked_widget.addWidget(self.home_page)
        self.settings_page = QtWidgets.QWidget()
        self.settings_page.setObjectName("settings_page")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.settings_page)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_2 = QtWidgets.QLabel(self.settings_page)
        self.label_2.setMaximumSize(QtCore.QSize(16777215, 15))
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_4.addWidget(self.label_2)
        self.frame_5 = QtWidgets.QFrame(self.settings_page)
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.frame_6 = QtWidgets.QFrame(self.frame_5)
        self.frame_6.setGeometry(QtCore.QRect(30, 30, 210, 47))
        self.frame_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.frame_6)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_5 = QtWidgets.QLabel(self.frame_6)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_4.addWidget(self.label_5)
        self.pathEdit = QtWidgets.QLineEdit(self.frame_6)
        self.pathEdit.setObjectName("pathEdit")
        self.horizontalLayout_4.addWidget(self.pathEdit)
        self.frame_7 = QtWidgets.QFrame(self.frame_5)
        self.frame_7.setGeometry(QtCore.QRect(250, 30, 151, 47))
        self.frame_7.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_7.setObjectName("frame_7")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.frame_7)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_6 = QtWidgets.QLabel(self.frame_7)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_5.addWidget(self.label_6)
        self.threadSP = QtWidgets.QSpinBox(self.frame_7)
        self.threadSP.setObjectName("threadSP")
        self.horizontalLayout_5.addWidget(self.threadSP)
        self.frame_8 = QtWidgets.QFrame(self.frame_5)
        self.frame_8.setGeometry(QtCore.QRect(580, 30, 151, 47))
        self.frame_8.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_8.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_8.setObjectName("frame_8")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.frame_8)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label_9 = QtWidgets.QLabel(self.frame_8)
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_8.addWidget(self.label_9)
        self.chooseCb = QtWidgets.QComboBox(self.frame_8)
        self.chooseCb.setObjectName("chooseCb")
        self.chooseCb.addItem("")
        self.chooseCb.addItem("")
        self.chooseCb.addItem("")
        self.chooseCb.addItem("")
        self.horizontalLayout_8.addWidget(self.chooseCb)
        self.frame_11 = QtWidgets.QFrame(self.frame_5)
        self.frame_11.setGeometry(QtCore.QRect(410, 30, 151, 47))
        self.frame_11.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_11.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_11.setObjectName("frame_11")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout(self.frame_11)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.label_10 = QtWidgets.QLabel(self.frame_11)
        self.label_10.setObjectName("label_10")
        self.horizontalLayout_9.addWidget(self.label_10)
        self.delaySP = QtWidgets.QDoubleSpinBox(self.frame_11)
        self.delaySP.setObjectName("delaySP")
        self.horizontalLayout_9.addWidget(self.delaySP)
        self.hidenTabCB = QtWidgets.QCheckBox(self.frame_5)
        self.hidenTabCB.setGeometry(QtCore.QRect(30, 90, 111, 41))
        self.hidenTabCB.setObjectName("hidenTabCB")
        self.delFileCB = QtWidgets.QCheckBox(self.frame_5)
        self.delFileCB.setGeometry(QtCore.QRect(150, 90, 151, 41))
        self.delFileCB.setObjectName("delFileCB")
        self.verticalLayout_4.addWidget(self.frame_5)
        self.main_stacked_widget.addWidget(self.settings_page)
        self.contact_page = QtWidgets.QWidget()
        self.contact_page.setObjectName("contact_page")
        self.label_3 = QtWidgets.QLabel(self.contact_page)
        self.label_3.setGeometry(QtCore.QRect(570, 150, 51, 21))
        self.label_3.setObjectName("label_3")
        self.main_stacked_widget.addWidget(self.contact_page)
        self.help_page = QtWidgets.QWidget()
        self.help_page.setObjectName("help_page")
        self.label_4 = QtWidgets.QLabel(self.help_page)
        self.label_4.setGeometry(QtCore.QRect(610, 140, 51, 21))
        self.label_4.setObjectName("label_4")
        self.main_stacked_widget.addWidget(self.help_page)
        self.gridLayout.addWidget(self.main_stacked_widget, 0, 0, 1, 1)
        self.horizontalLayout.addWidget(self.frame_4)
        self.verticalLayout.addWidget(self.frame_2)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.main_stacked_widget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.homeBtn.setText(_translate("MainWindow", "Trang chủ"))
        self.settingsBtn.setText(_translate("MainWindow", "Cài đặt"))
        self.contactBtn.setText(_translate("MainWindow", "Liên hệ"))
        self.helpBtn.setText(_translate("MainWindow", "Trợ giúp"))
        self.label.setText(_translate("MainWindow", "Trang chủ"))
        self.label_selected.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:600; color:#0000ff;\">Đã chọn: </span><span style=\" font-weight:600;\">0</span></p></body></html>"))
        self.label_success.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:600; color:#00aa00;\">Thành công: </span><span style=\" font-weight:600;\">0</span></p></body></html>"))
        self.label_failed.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:600; color:#ff0000;\">Thất bại: </span><span style=\" font-weight:600;\">0</span></p></body></html>"))
        self.label_2.setText(_translate("MainWindow", "Cài đặt"))
        self.label_5.setText(_translate("MainWindow", "Đường dẫn:"))
        self.label_6.setText(_translate("MainWindow", "số luồng:"))
        self.label_9.setText(_translate("MainWindow", "Chọn:"))
        self.chooseCb.setItemText(0, _translate("MainWindow", "1"))
        self.chooseCb.setItemText(1, _translate("MainWindow", "2"))
        self.chooseCb.setItemText(2, _translate("MainWindow", "3"))
        self.chooseCb.setItemText(3, _translate("MainWindow", "4"))
        self.label_10.setText(_translate("MainWindow", "Độ trễ"))
        self.hidenTabCB.setText(_translate("MainWindow", "Ẩn tab"))
        self.delFileCB.setText(_translate("MainWindow", "Xoá file sau khi xong"))
        self.label_3.setText(_translate("MainWindow", "Liên hệ"))
        self.label_4.setText(_translate("MainWindow", "Hỗ trợ"))
